export enum CardType {
  TimelineCard = 'TimelineCard',
  FieldCard = 'FieldCard',
  RichTextCard = 'RichTextCard',
  TaskCard = 'TaskCard',
  NoteCard = 'NoteCard',
  FileCard = 'FileCard',
  EmailCard = 'EmailCard',
  CalendarCard = 'CalendarCard',
  WorkflowCard = 'WorkflowCard',
  WorkflowVersionCard = 'WorkflowVersionCard',
  WorkflowRunCard = 'WorkflowRunCard',
  WorkflowRunOutputCard = 'WorkflowRunOutputCard',
  OverviewCard = 'OverviewCard',
  AISuiteCard = 'AISuiteCard',
  PublicationDetailsCard = 'PublicationDetailsCard',
  PropertyInquiriesListCard = 'PropertyInquiriesListCard',
  MobilePublicationsCard = 'MobilePublicationsCard',
  PublicationListCard = 'PublicationListCard',
  MarketingSuiteCard = 'MarketingSuiteCard',
}
