export enum TutorialStatus {
  TUTORIAL_PLATFORM_SETUP = 'TUTORIAL_PLATFORM_SETUP',
  TUTORIAL_EMAIL = 'TUTORIAL_EMAIL',
  TUTORIAL_PROPERTY = 'TUTORIAL_PROPERTY',
  TUTORIAL_PUBLICATION = 'TUTORIAL_PUBLICATION',
  TUTORIAL_COMPLETED = 'TUTORIAL_COMPLETED',
}
